import { cloneData } from "./model.js?v=20260929.10";
import { getActiveSyllableId } from "./lyrics.js";

const AVAILABLE_ACTIONS = Object.freeze([
  "getSong",
  "getSelection",
  "getSelectedNoteIds",
  "addNote",
  "updateNote",
  "updateNotes",
  "deleteNote",
  "addPercussionHit",
  "updatePercussionHit",
  "deletePercussionHit",
  "setLyrics",
  "setAnchor",
  "setLocked",
  "selectRange",
  "selectNotes",
  "clearSelection",
  "copySelection",
  "pasteNotes",
  "setSnap",
  "setTool",
  "setZoom",
  "addLyricSyllable",
  "updateLyricSyllable",
  "deleteLyricSyllable",
  "splitLyricSyllable",
  "mergeLyricSyllables",
  "moveLyricSyllable",
  "assignSyllableNotes",
  "newIdea",
  "loadSong",
  "generateGap",
  "getGenerationState",
  "selectCandidate",
  "auditionCandidate",
  "acceptCandidate",
  "lockAcceptedNotes",
  "clearGeneration",
  "regenerateGap",
  "play",
  "pause",
  "stop",
  "seek",
  "setTempo",
  "setLoop",
  "resetLoopRange",
  "setLoopEnabled",
  "setViewMode",
  "setFollowMode",
  "undo",
  "redo",
  "canUndo",
  "canRedo"
]);

export function createAgentSnapshot(song, selection, playback = {
  status: "stopped",
  currentTick: 0,
  currentNoteId: null,
  currentSectionId: song.sections[0]?.id ?? null,
  tempo: song.timing.tempo,
  loop: { enabled: false, startTick: 0, endTick: 1 }
}, editor = { snap: "1/8", tool: "select", canPaste: false, clipboardCount: 0 }, selectedNoteIds = [], view = { mode: "combined", follow: true }, generation = {
  status: "idle",
  stale: false,
  gap: null,
  seed: null,
  candidateIds: [],
  activeCandidateId: null,
  auditionCandidateId: null,
  candidates: [],
  acceptedNoteIds: []
}, history = { canUndo: false, canRedo: false, undoDepth: 0, redoDepth: 0 }) {
  const currentSyllableId = getActiveSyllableId(song.lyrics, playback.currentNoteId);
  const currentSyllableIds = currentSyllableId ? [currentSyllableId] : [];
  return {
    song: {
      id: song.id,
      title: song.title,
      tempo: song.timing.tempo,
      key: song.key,
      scale: cloneData(song.scale),
      timeSignature: cloneData(song.timing.timeSignature),
      currentSectionId: playback.currentSectionId,
      notes: cloneData(song.notes),
      lyrics: cloneData(song.lyrics),
      sections: cloneData(song.sections),
      phrases: cloneData(song.phrases),
      chords: cloneData(song.chords),
      tracks: cloneData(song.tracks)
    },
    playback: {
      status: playback.status,
      currentTick: playback.currentTick,
      currentNoteId: playback.currentNoteId,
      currentSyllableId,
      currentSyllableIds,
      currentSectionId: playback.currentSectionId,
      tempo: playback.tempo,
      loop: cloneData(playback.loop)
    },
    selection: cloneData(selection),
    selectedNoteIds: cloneData(selectedNoteIds),
    editor: cloneData(editor),
    view: cloneData(view),
    generation: cloneData(generation),
    anchorNoteIds: song.notes.filter((note) => note.anchor).map((note) => note.id),
    lockedNoteIds: song.notes.filter((note) => note.locked).map((note) => note.id),
    history: cloneData(history),
    availableActions: [...AVAILABLE_ACTIONS]
  };
}
